image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd midi_app && flutter config --enable-web && flutter pub get
    command: cd midi_app && flutter run -d chrome

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - Dart-Code.flutter